[tool.poetry]
name = "home_automation"
version = "0.1.0"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.1"
requests = "^2.27.1"
pandas = "^1.4.2"
panel = "^0.13.1"
bokeh = "^2.4.3"
pandas-bokeh = "^0.5.5"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.19.0"
black = "^22.3.0"
pytest-dotenv = "^0.5.2"
jupyter = "^1.0.0"
jupyter-bokeh = "^3.0.4"
matplotlib = "^3.5.2"
detect-secrets = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
