[tool.poetry]
name = "home_automation"
version = "0.1.0"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.0"
requests = "^2.28.1"
pandas = "^1.4.3"
tabulate = "^0.8.10"
matplotlib = "^3.5.2"
Markdown = "^3.4.1"
statsd = "^3.3.0"
influxdb = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pre-commit = "^2.20.0"
black = "^22.6.0"
pytest-dotenv = "^0.5.2"
jupyter = "^1.0.0"
detect-secrets = "^1.3.0"
flake8 = "^5.0.4"
bandit = "^1.7.4"
interrogate = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
