[tool.poetry]
name = "home_automation"
version = "0.1.1"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
requests = "^2.28.1"
pandas = "^1.5.2"
tabulate = "^0.9.0"
matplotlib = "^3.5.3"
Markdown = "^3.4.1"
statsd = "^4.0.1"
influxdb = "^5.3.1"
google-api-python-client = "^2.66.0"
google-auth = "^2.14.1"
google-auth-oauthlib = "^0.7.1"
google-auth-httplib2 = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pre-commit = "^2.20.0"
black = "^22.12.0"
pytest-dotenv = "^0.5.2"
jupyter = "^1.0.0"
detect-secrets = "^1.3.0"
flake8 = "^6.0.0"
bandit = "^1.7.4"
interrogate = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
