apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: rundeck

# This file must be created by your deployment tools, we use Ansible. See ansible
# deployments for creating.
secretGenerator:
- envs:
  - .env
  name: credentials
images:
- name: ghcr.io/davidasnider/home_automation
  newTag: v1.0.300
