---
apiVersion: batch/v1
kind: Job
metadata:
  name: calc-sprinkler-multiplier
  labels:
    app: home_automation
spec:
  template:
    spec:
      containers:
        - name: sprinkler-multiplier
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: credentials
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-magic-mirror-temp
  labels:
    app: home_automation
spec:
  template:
    spec:
      containers:
        - name: update-magic-mirror-temp
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - /app/update_magic_mirror_temp.py
          envFrom:
          - secretRef:
              name: credentials
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: log-indigo-metrics
  labels:
    app: home_automation
spec:
  template:
    spec:
      containers:
        - name: log-indigo-metrics
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - /app/log_indigo_metrics.py
          envFrom:
          - secretRef:
              name: credentials
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: log-netatmo
  labels:
    app: home_automation
spec:
  template:
    spec:
      containers:
        - name: log-netatmo
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - /app/log_netatmo.py
          envFrom:
          - secretRef:
              name: credentials
      restartPolicy: Never
  backoffLimit: 4
