---
apiVersion: batch/v1
kind: Job
metadata:
  name: calc-sprinkler-multiplier
  labels:
    app: home_automation
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: sprinkler-multiplier
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          env:
            - name: indigo_password
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: indigo_password
            - name: indigo_username
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: indigo_username
            - name: tmrw_location_id
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: tmrw_location_id
            - name: tomorrow_io
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: tomorrow_io
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-magic-mirror-temp
  labels:
    app: home_automation
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: update-magic-mirror-temp
          image: ghcr.io/davidasnider/home_automation:v1.0.13
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - /app/update_magic_mirror_temp.py
          env:
            - name: indigo_password
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: indigo_password
            - name: indigo_username
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: indigo_username
      restartPolicy: Never
  backoffLimit: 4
