name: Test Build Merge Deploy

on:
  pull_request:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/davidasnider/home_automation

jobs:
  set-version-tags:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-prep.outputs.version }}
      tags: ${{ steps.build-prep.outputs.tags }}
    steps:
      - name: Set version tags
        id: build-prep
        run: |
          VERSION=noop
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=v1.0.${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAGS=${TAGS}" >> $GITHUB_ENV
          echo "CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

  build-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

  build-primary-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push primary container
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ $env.TAGS }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-name
      - build-primary-container

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kubernetes resources
        run: |
          cd deploy/base
          kustomize edit set image ${{ $env.TAGS }}
          cat kustomization.yaml
          cd ../dev
          kustomize edit set image ${{ $env.TAGS }}
          cat kustomization.yaml
          cd ../prod
          kustomize edit set image ${{ $env.TAGS }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}

  pr-approve:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: hmarr/auto-approve-action@v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  label-pr:
    runs-on: ubuntu-latest
    needs:
      - pr-approve
    steps:
      - uses: christianvuerings/add-labels@v1.1
        with:
          labels: |
            automerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    needs:
      - label-pr
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
